### ISSUE TITLE
Request param with empty array is not sent

### ISSUE THREAD

**Issue by razor-x** [seamapi/javascript#251]
Related to https://stackoverflow.com/questions/60682549/how-can-i-force-axios-to-send-empty-array

**Comment by chamokk** [comment]
Hey Razor!

I'd like to contribute and fix this issue, could you provide a use case or example of where it happens in the project?

**Comment by razor-x** [comment]
Hi @chamokk that's great! I am setting up some new test infra, and I can make sure I reproduce this in a failing test for you, then I'd be happy to accept a fix. I should have that ready early next week.

**Comment by chamokk** [comment]
Hey @razor-x , how it's all progressing?

**Comment by razor-x** [comment]
@chamokk 

Hi, let me give you an update on the overall situation:

- We are working on upgrading this package to use a generated client.
- The new client will be maintained at https://github.com/seamapi/javascript-http
- That repo will ensure all types / methods are up date and have much better test coverage, especially for for edge cases like this serialization issue.
- Once the new client is ready and tested, we will re-export it from this package with a migration plan. We will make sure the migration is simple for existing users.

The generated client currently always uses `POST` as the method and sends params in the body. All Seam API endpoints support POST and behavior does not change based on the method used. In this mode, there are no serialization concerns. 

We realize that using `GET` for read-only endpoints is important in some contexts, so the client will eventually either use GET for those endpoints, or allow the caller to opt in to `GET`. Thus, we still want to support reliable serialization.

I believe this PR on the new client addresses the serialization issue. The API should treat params like `foo=` as the empty array when the param is documented as an array type. I realized there is a possible ambiguity between `foo=` meaning `[]` or `['']`. The API will parse this as `[]`. I do not believe there is any use case where `['']` would be meaningful, or return different results than `[]`, but let me know if you can think of an example.

https://github.com/seamapi/javascript-http/pull/8

There are two ways you can help us here:

1. Review the PR and let me know if you think this is a good solution, missing edge cases or tests, etc. https://github.com/seamapi/javascript-http/pull/8
2. Backport the function in the PR to this repo, or update all GET endpoints in this SDK to use POST instead of GET. This will solve the issues for people today, and all the while they are still on this version of the SDK until they eventually can migrate.
